# Generated by Django 5.0.9 on 2024-10-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="age",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
